### ISSUE TITLE
Does deployment really need the AWS Marketplace subscribed?

### ISSUE THREAD

**Issue by shahbazalam8** [wazuh/wazuh-cloudformation#34]
When i am using master branch for deployment the script failing to fetch the windows ami and centos ami saying we should subscribe to AWS Market place.

if i am replace the AMI with quick start AMIs then its deploying but getting error like below.

![image](https://user-images.githubusercontent.com/35764530/71165189-74d7b380-2276-11ea-99d7-5e606c8b51eb.png)

Check Wazuh API connection |  
-- | --
Check for Wazuh API version |  
Check Elasticsearch index pattern | Ready
Check Elasticsearch template | Ready
Check index pattern known fields | Ready

Health Check. 3002 - Invalid 'wazuh-app-version' header. Expected version '3.11.x', and found '3.10.x'. (/api/check-stored-api)

**Comment by manuasir** [comment]
Hello @shahbazalam8 ,

Because we take the AMIs directly from AWS Marketplace, which could explain your error if your IAM role does not have the proper permissions to access it.
Regarding the error, let us verify the master branch because it seems that it's taking the development `3.11` installation of the Wazuh API. 
I'll get back to you ASAP.

Cheers

**Comment by manuasir** [comment]
Hello @shahbazalam8 ,

We couldn't verify that there was a conflict between the Wazuh UI plugin and the API version. If you're still facing this problem, please open a new ticket.

Regards
