### ISSUE TITLE
Ubuntu Server 16.04 and/or 18.04 support request

### ISSUE THREAD

**Issue by troal** [wazuh/wazuh-cloudformation#8]
Hello,
Would that be possible to include Ubuntu Server 18.04 and/or Ubuntu Server 16.04 OS support for core servers?
- Wazuh master/worker
- Elastic cluster members
- Kibana/Splunk servers
Thanks!

**Comment by manuasir** [comment]
Hello @troal ,

We've been using Amazon Linux because of the facilities that it provides for the provisioning time, due to they already have the `aws cf` bootstrapping binaries, otherwise we should implement something like this on each `userData` section in the template:

https://github.com/wazuh/wazuh-cloudformation/blob/be2c7703090c25c155cf0535a549e9a72b42b883/wazuh_template.yml#L1711-L1720

I hope that helps.

Regards

**Comment by manuasir** [comment]
Hello @troal ,

I just wanted to follow up this issue. Were you able to resolve it? Let me know if you still need help with this or if we can close this issue.

Cheers

**Comment by troal** [comment]
Hello @manuasir,
Thanks for your answer. My request was more to have a native support of Ubuntu 16.04 and/or 18.04 for core servers directly as an option in the AWS cloudformation template.
I understand it would bring more work to maintain both the template and deployment scripts also just let me know if you don't want to include it in your roadmap.

**Comment by manuasir** [comment]
Hello @troal ,

Thanks so much for this suggestion, really appreciated. But finally, we decided that this won't be included in our roadmap. Please, don't hesitate to collaborate again with more suggestions or opening a new PR.

Regards
